export const flavorlists = [
  {
    name: "Chocolate Milk",
    color: "brown",
    rotation: "md:rotate-[-8deg] rotate-0",
    accent: "#7B3F1E",
    glow: "#C4622D",
    tag: "Classic",
    calories: 320,
    tagline: "Rich. Velvety. Timeless.",
  },
  {
    name: "Strawberry Milk",
    color: "red",
    rotation: "md:rotate-[8deg] rotate-0",
    accent: "#D72638",
    glow: "#FF6B8A",
    tag: "Fan Fave",
    calories: 290,
    tagline: "Sweet. Fruity. Dreamy.",
  },
  {
    name: "Cookies & Cream",
    color: "blue",
    rotation: "md:rotate-[-8deg] rotate-0",
    accent: "#2D3A8C",
    glow: "#6C8FFF",
    tag: "Limited",
    calories: 360,
    tagline: "Crunchy. Creamy. Addictive.",
  },
  {
    name: "Peanut Butter Chocolate",
    color: "orange",
    rotation: "md:rotate-[8deg] rotate-0",
    accent: "#C4500A",
    glow: "#FF8C42",
    tag: "Power Up",
    calories: 410,
    tagline: "Bold. Nutty. Unstoppable.",
  },
  {
    name: "Vanilla Milkshake",
    color: "white",
    rotation: "md:rotate-[-8deg] rotate-0",
    accent: "#E8D5A3",
    glow: "#FFF5D6",
    tag: "Pure",
    calories: 270,
    tagline: "Smooth. Soft. Luxurious.",
  },
  {
    name: "Max Chocolate Milk",
    color: "black",
    rotation: "md:rotate-[8deg] rotate-0",
    accent: "#1A1A1A",
    glow: "#5C3317",
    tag: "Intense",
    calories: 380,
    tagline: "Dark. Deep. Devastating.",
  },
];

export const nutrientLists = [
  {
    label: "Potassium",
    amount: "245mg",
    icon: "⚡",
    percent: 52,
    color: "#F59E0B",
    description: "Supports muscle function",
  },
  {
    label: "Calcium",
    amount: "500mg",
    icon: "🦴",
    percent: 88,
    color: "#60A5FA",
    description: "Builds strong bones",
  },
  {
    label: "Vitamin A",
    amount: "176mcg",
    icon: "👁",
    percent: 65,
    color: "#F97316",
    description: "Supports healthy vision",
  },
  {
    label: "Vitamin D",
    amount: "5mcg",
    icon: "☀️",
    percent: 70,
    color: "#FBBF24",
    description: "Boosts immunity & mood",
  },
  {
    label: "Iron",
    amount: "1mg",
    icon: "💪",
    percent: 30,
    color: "#EF4444",
    description: "Carries oxygen in blood",
  },
];

export const cards = [
  {
    src: "/videos/f1.mp4",
    deg: -10,                         // ← clean number used by TestimonialSection
    name: "Madison",
    img: "/images/p1.png",
    role: "Athlete",
    quote: "My daily fuel before every race.",
    rating: 5,
  },
  {
    src: "/videos/f2.mp4",
    deg: 4,
    name: "Alexander",
    img: "/images/p2.png",
    role: "Bodybuilder",
    quote: "Nothing hits like post-workout Spylt.",
    rating: 5,
  },
  {
    src: "/videos/f3.mp4",
    deg: -4,
    name: "Andrew",
    img: "/images/p3.png",
    role: "CrossFit Coach",
    quote: "I recommend it to all my clients.",
    rating: 5,
  },
  {
    src: "/videos/f4.mp4",
    deg: 4,
    name: "Bryan",
    img: "/images/p4.png",
    role: "Nutritionist",
    quote: "Finally, a shake that actually tastes good.",
    rating: 4,
  },
  {
    src: "/videos/f5.mp4",
    deg: -8,
    name: "Chris",
    img: "/images/p5.png",
    role: "Cyclist",
    quote: "Keeps me going for miles and miles.",
    rating: 5,
  },
  {
    src: "/videos/f6.mp4",
    deg: 4,
    name: "Devante",
    img: "/images/p6.png",
    role: "Trainer",
    quote: "Obsessed with the Peanut Butter flavor.",
    rating: 5,
  },
  {
    src: "/videos/f7.mp4",
    deg: -3,
    name: "Melisa",
    img: "/images/p7.png",
    role: "Yoga Instructor",
    quote: "Light, smooth, and never too heavy.",
    rating: 5,
  },
];

export const stats = [
  { value: "6",  label: "Unique Flavours",   suffix: ""  },
  { value: "50", label: "Grams of Protein",  suffix: "g" },
  { value: "500",label: "mg of Calcium",     suffix: "+" },
  { value: "1M", label: "Happy Customers",   suffix: "+" },
];

export const faqs = [
  {
    question: "Are Spylt drinks suitable for lactose intolerance?",
    answer: "We offer a lactose-free variant for all our flavors. Look for the 'LF' badge on the packaging.",
  },
  {
    question: "How much protein is in each bottle?",
    answer: "Each 250ml bottle contains between 28–50g of high-quality whey protein depending on the variant.",
  },
  {
    question: "Where can I buy Spylt?",
    answer: "Available in-store at major supermarkets, gyms, and online via our website with next-day delivery.",
  },
  {
    question: "Are there any artificial sweeteners?",
    answer: "Zero. We use only natural flavoring agents and cane sugar. No aspartame, no sucralose.",
  },
  {
    question: "What's the shelf life?",
    answer: "Unopened bottles last 12 months. Once opened, refrigerate and consume within 48 hours.",
  },
];